-- Auth
create table users (
    id            bigint generated by default as identity primary key,
    username      varchar(255) not null unique,
    password_hash varchar(255) not null,
    role          varchar(20)  not null,
    active        boolean      not null default true,
    created_at    timestamp    not null,
    updated_at    timestamp    not null
);

create table user_rights (
    user_id   bigint       not null references users(id) on delete cascade,
    right_key varchar(100) not null
);

-- Attendance module
create table designations (
    id         bigint generated by default as identity primary key,
    name       varchar(255) not null unique,
    created_at timestamp    not null,
    updated_at timestamp    not null
);

create table employees (
    id                      bigint generated by default as identity primary key,
    emp_id                  varchar(20)    not null unique,
    name                    varchar(255)   not null,
    address                 varchar(500),
    aadhar                  varchar(20)    not null,
    phone                   varchar(20)    not null,
    designation_id          bigint         not null references designations(id),
    date_of_joining         date           not null,
    salary_type             varchar(20)    not null,
    salary                  numeric(12, 2),
    pc_rate                 numeric(12, 2),
    contractor_name         varchar(255),
    emp_type                varchar(20)    not null default 'REGULAR',
    valid_till              date,
    department              varchar(255),
    notes                   varchar(2000),
    photo_url               varchar(500),
    active                  boolean        not null default true,
    created_at              timestamp      not null,
    updated_at              timestamp      not null
);

create table employee_authorized_workstations (
    employee_id     bigint       not null references employees(id) on delete cascade,
    workstation_code varchar(50) not null
);

create table attendance_records (
    id               bigint generated by default as identity primary key,
    date             date      not null,
    employee_id      bigint    not null references employees(id),
    designation_id   bigint    not null references designations(id),
    entry_time       time,
    exit_time        time,
    entered_by_id    bigint references users(id),
    entered_at       timestamp not null,
    last_edited_by_id bigint references users(id),
    last_edited_at   timestamp,
    created_at       timestamp not null,
    updated_at       timestamp not null,
    constraint uk_attendance_date_employee unique (date, employee_id)
);

-- No admin is seeded here. The initial admin is created at startup by AdminBootstrap
-- from ERP_ADMIN_PASSWORD (required in prod, a random logged-once value in dev), so no
-- known default credential ever ships in the schema.
