-- Production module: workstations/operations, PC rates, jobs + routing,
-- production entries, QC + rework, operation closures, transfer challans.
--
-- Design notes (deviations from the legacy Firestore-array model, see
-- com.niic.erp.production package-info for the full research writeup):
--   * Legacy job numbers were a single global counter (despite a stale code
--     comment claiming "per style") allocated via a non-atomic client-side
--     read-increment-write. We preserve the *global* numbering behavior
--     (business continuity) but make it atomic via a real DB sequence.
--   * Legacy transfer challan numbers reset per calendar year (TC-26-0001).
--     There's no portable "sequence that resets yearly" in standard SQL, so
--     we use a small counter table with pessimistic locking instead.
--   * Job requests and routing change requests are disposable staging data —
--     once approved they're copied into the real jobs/routing tables and
--     never read again in their original form. Duplicating the full
--     job/routing relational shape for that staging step isn't worth it, so
--     their colour/size/routing payload is stored as JSON text and parsed
--     only at review time.
--   * fg_item_id / variant_id / item_id columns reference the not-yet-built
--     Store module (fstore_items / fstore_variants). Left as plain bigint
--     with no FK constraint until that module exists.

create sequence job_number_seq start with 1 increment by 1;

create table styles (
    id         bigint generated by default as identity primary key,
    code       varchar(50)  not null unique,
    label      varchar(255) not null,
    active  boolean      not null default true,
    created_at timestamp    not null,
    updated_at timestamp    not null
);

insert into styles (code, label, active, created_at, updated_at) values
    ('SLIP-ONS', 'Slip-Ons', true, current_timestamp, current_timestamp),
    ('MINI-SHOES', 'Mini Shoes', true, current_timestamp, current_timestamp),
    ('HOPPER', 'Hopper', true, current_timestamp, current_timestamp),
    ('BOTTLE-COVER', 'Bottle Cover', true, current_timestamp, current_timestamp),
    ('SOLE-SHOES', 'Sole Shoes', true, current_timestamp, current_timestamp),
    ('MINI-SANDAL', 'Mini Sandal', true, current_timestamp, current_timestamp);

create table workstations (
    id         bigint generated by default as identity primary key,
    name       varchar(255) not null unique,
    code       varchar(50),
    active  boolean      not null default true,
    created_at timestamp    not null,
    updated_at timestamp    not null
);

create table operations (
    id             bigint generated by default as identity primary key,
    workstation_id bigint       not null references workstations(id),
    name           varchar(255) not null,
    active      boolean      not null default true,
    created_at     timestamp    not null,
    updated_at     timestamp    not null,
    constraint uk_operation_wst_name unique (workstation_id, name)
);

create table pc_rates (
    id             bigint generated by default as identity primary key,
    workstation_id bigint         not null references workstations(id),
    style          varchar(50)    not null references styles(code),
    model_no       varchar(255)   not null,
    operation_id   bigint         not null references operations(id),
    rate           numeric(12, 2) not null,
    effective_date date           not null,
    active      boolean        not null default true,
    created_by_id  bigint references users(id),
    created_at     timestamp      not null,
    updated_at     timestamp      not null
);
create index ix_pc_rates_lookup on pc_rates (workstation_id, operation_id, active);

-- Jobs -----------------------------------------------------------------

create table jobs (
    id                 bigint generated by default as identity primary key,
    job_display_id     varchar(100) not null unique,
    style              varchar(50)  not null references styles(code),
    model_no           varchar(255) not null,
    fg_item_id         bigint,
    unit               varchar(20)  not null,
    total_planned_qty  integer      not null default 0,
    active          boolean      not null default true,
    source             varchar(30)  not null,
    routing_assigned   boolean      not null default false,
    created_by_id      bigint       references users(id),
    created_at         timestamp    not null,
    updated_at         timestamp    not null
);

create table job_colours (
    id       bigint generated by default as identity primary key,
    job_id   bigint       not null references jobs(id) on delete cascade,
    name     varchar(255) not null,
    seq      integer      not null
);

create table job_sizes (
    id           bigint generated by default as identity primary key,
    job_colour_id bigint      not null references job_colours(id) on delete cascade,
    size         varchar(100) not null,
    planned_qty  integer      not null,
    variant_id   bigint,
    seq          integer      not null
);

create table job_requests (
    id             bigint generated by default as identity primary key,
    style          varchar(50)  not null references styles(code),
    model_no       varchar(255) not null,
    fg_item_id     bigint,
    unit           varchar(20)  not null,
    colours_json   text         not null,
    status         varchar(20)  not null default 'PENDING',
    requested_by_id bigint      not null references users(id),
    reviewed_by_id  bigint      references users(id),
    reviewed_at     timestamp,
    admin_remark    varchar(2000),
    created_at      timestamp   not null,
    updated_at      timestamp   not null
);

-- Routing ----------------------------------------------------------------

create table routing (
    id            bigint generated by default as identity primary key,
    job_id        bigint    not null unique references jobs(id),
    created_by_id bigint    references users(id),
    updated_by_id bigint    references users(id),
    created_at    timestamp not null,
    updated_at    timestamp not null
);

create table routing_workstations (
    id             bigint generated by default as identity primary key,
    routing_id     bigint  not null references routing(id) on delete cascade,
    seq            integer not null,
    workstation_id bigint  not null references workstations(id)
);

create table routing_operations (
    id                     bigint generated by default as identity primary key,
    routing_workstation_id bigint  not null references routing_workstations(id) on delete cascade,
    seq                    integer not null,
    operation_id           bigint  not null references operations(id)
);

-- Self-referential: an operation step can depend on other steps in the same
-- routing (a DAG, not just workstation order) — see _buildRoutingSteps in the
-- legacy code for the "available qty capped by min(done qty of dependencies)"
-- algorithm this supports.
create table routing_operation_dependencies (
    routing_operation_id bigint not null references routing_operations(id) on delete cascade,
    depends_on_id         bigint not null references routing_operations(id) on delete cascade,
    primary key (routing_operation_id, depends_on_id)
);

create table routing_change_requests (
    id                  bigint generated by default as identity primary key,
    job_id              bigint       not null references jobs(id),
    proposed_routing_json text       not null,
    reason              varchar(2000) not null,
    status              varchar(20)  not null default 'PENDING',
    requested_by_id     bigint       not null references users(id),
    reviewed_by_id      bigint       references users(id),
    reviewed_at         timestamp,
    admin_remark        varchar(2000),
    created_at          timestamp    not null,
    updated_at          timestamp    not null
);

-- Production entries -------------------------------------------------------

create table production_entries (
    id                    bigint generated by default as identity primary key,
    date                  date      not null,
    employee_id           bigint    not null references employees(id),
    job_id                bigint    not null references jobs(id),
    colour_id             bigint    references job_colours(id),
    size_id               bigint    references job_sizes(id),
    side                  varchar(10),
    unit                  varchar(20) not null,
    entered_by_id         bigint    references users(id),
    entered_at            timestamp not null,
    last_edited_by_id     bigint    references users(id),
    last_edited_at        timestamp,
    is_approved_edit       boolean   not null default false,
    approved_edit_request_id bigint,
    created_at            timestamp not null,
    updated_at            timestamp not null
);
create index ix_prod_entries_merge_key on production_entries (date, employee_id, job_id, colour_id, size_id, side);

create table production_entry_ops (
    id                  bigint generated by default as identity primary key,
    production_entry_id bigint  not null references production_entries(id) on delete cascade,
    workstation_id      bigint  not null references workstations(id),
    operation_id        bigint  not null references operations(id),
    quantity            integer not null,
    unit                varchar(20) not null,
    constraint uk_prod_entry_op unique (production_entry_id, workstation_id, operation_id)
);

create table production_edit_requests (
    id               bigint generated by default as identity primary key,
    job_id           bigint       not null references jobs(id),
    colour_id        bigint       references job_colours(id),
    size_id          bigint       references job_sizes(id),
    requested_by_id  bigint       not null references users(id),
    requested_at     timestamp    not null,
    reason           varchar(2000) not null,
    status           varchar(20)  not null default 'PENDING',
    used             boolean      not null default false,
    used_at          timestamp,
    resolved_by_id   bigint       references users(id),
    resolved_at      timestamp,
    resolution       varchar(2000),
    created_at       timestamp    not null,
    updated_at       timestamp    not null
);

alter table production_entries
    add constraint fk_prod_entry_edit_req foreign key (approved_edit_request_id) references production_edit_requests(id);

-- Operation closures ---------------------------------------------------

create table operation_closures (
    id                  bigint generated by default as identity primary key,
    job_id              bigint       not null references jobs(id),
    colour_id           bigint       references job_colours(id),
    size_id             bigint       references job_sizes(id),
    workstation_id      bigint       not null references workstations(id),
    operation_id        bigint       not null references operations(id),
    done_qty_at_closure integer      not null,
    planned_qty         integer      not null,
    reason              varchar(30)  not null,
    rework_qty          integer,
    rejection_qty       integer,
    notes               varchar(2000),
    closed_by_id        bigint       not null references employees(id),
    date                date         not null,
    created_at          timestamp    not null,
    updated_at          timestamp    not null,
    constraint uk_op_closure unique (job_id, colour_id, size_id, workstation_id, operation_id)
);

-- QC + rework --------------------------------------------------------------

create table qc_entries (
    id                 bigint generated by default as identity primary key,
    date               date         not null,
    job_id             bigint       not null references jobs(id),
    colour_id          bigint       references job_colours(id),
    size_id            bigint       references job_sizes(id),
    side               varchar(10),
    unit               varchar(20)  not null,
    op_ref             varchar(255),
    workstation_id     bigint       references workstations(id),
    total_checked      integer      not null,
    pass_qty           integer      not null default 0,
    alter_qty          integer      not null default 0,
    reject_qty         integer      not null default 0,
    status             varchar(20)  not null,
    from_qc_workstation boolean     not null default false,
    notes              varchar(2000),
    entered_by_id      bigint       references users(id),
    entered_at         timestamp    not null,
    updated_by_id      bigint       references users(id),
    updated_at_business timestamp,
    created_at         timestamp    not null,
    updated_at         timestamp    not null
);

create table qc_rework (
    id             bigint generated by default as identity primary key,
    qc_entry_id    bigint       not null references qc_entries(id),
    date           date         not null,
    job_id         bigint       not null references jobs(id),
    colour_id      bigint       references job_colours(id),
    size_id        bigint       references job_sizes(id),
    side           varchar(10),
    alter_qty      integer      not null,
    rework_done    integer      not null default 0,
    rework_reject  integer      not null default 0,
    status         varchar(20)  not null default 'PENDING',
    notes          varchar(2000),
    entered_by_id  bigint       references users(id),
    entered_at     timestamp    not null,
    updated_by_id  bigint       references users(id),
    updated_at_business timestamp,
    created_at     timestamp    not null,
    updated_at     timestamp    not null
);

-- Transfer challans ----------------------------------------------------

create table challan_number_counters (
    challan_year integer primary key,
    last_number  integer not null
);

create table transfer_challans (
    id                bigint generated by default as identity primary key,
    challan_no        varchar(30)  not null unique,
    job_id            bigint       not null references jobs(id),
    from_workstation_id bigint     not null references workstations(id),
    to_workstation_id   bigint     not null references workstations(id),
    remarks           varchar(2000),
    status            varchar(20)  not null default 'PENDING',
    created_by_id     bigint       not null references users(id),
    created_at        timestamp    not null,
    received_by_id    bigint       references users(id),
    received_at       timestamp,
    rejected_by_id    bigint       references users(id),
    rejected_at       timestamp,
    rejection_reason  varchar(2000),
    updated_at        timestamp    not null
);

create table transfer_challan_items (
    id                  bigint generated by default as identity primary key,
    transfer_challan_id bigint         not null references transfer_challans(id) on delete cascade,
    item_id             bigint,
    item_code           varchar(100),
    item_name           varchar(255)   not null,
    item_unit           varchar(20)    not null,
    qty                 numeric(12, 2) not null
);
