-- Payroll module: advances, monthly payroll runs (salaried + PC-rate wage
-- computation) and contractor bills. Wage formulas are ported from the legacy
-- attendance module (see com.niic.erp.payroll.PayrollService) — per-day = salary/26,
-- overtime = max(0, workedMinutes-480) priced at salary/(26*480) per minute, and
-- PC-rate gross = pieces * employee pcRate.

create table payroll_advances (
    id            bigint generated by default as identity primary key,
    employee_id   bigint         not null references employees(id),
    period_month  varchar(7)     not null,
    amount        numeric(14, 2) not null,
    reason        varchar(500),
    deducted      boolean        not null default false,
    created_at    timestamp      not null,
    updated_at    timestamp      not null
);

create index idx_advances_month on payroll_advances(period_month);
create index idx_advances_emp_month on payroll_advances(employee_id, period_month);

create table payroll_runs (
    id            bigint generated by default as identity primary key,
    period_month  varchar(7)  not null,
    status        varchar(20) not null default 'DRAFT',
    finalized_at  timestamp,
    created_at    timestamp   not null,
    updated_at    timestamp   not null
);

create index idx_runs_month on payroll_runs(period_month);

create table payroll_run_lines (
    id                bigint generated by default as identity primary key,
    run_id            bigint         not null references payroll_runs(id) on delete cascade,
    employee_id       bigint         not null references employees(id),
    salary_type       varchar(20)    not null,
    present_days      integer        not null default 0,
    overtime_minutes  integer        not null default 0,
    total_pieces      integer        not null default 0,
    monthly_salary    numeric(14, 2),
    pc_rate           numeric(14, 2),
    gross_pay         numeric(14, 2) not null,
    advances_deducted numeric(14, 2) not null,
    net_pay           numeric(14, 2) not null,
    created_at        timestamp      not null,
    updated_at        timestamp      not null
);

create table contractors (
    id         bigint generated by default as identity primary key,
    name       varchar(255) not null,
    phone      varchar(30),
    active     boolean      not null default true,
    created_at timestamp    not null,
    updated_at timestamp    not null
);

create table contractor_bills (
    id                bigint generated by default as identity primary key,
    contractor_id     bigint         not null references contractors(id),
    period_month      varchar(7)     not null,
    rate_type         varchar(20)    not null,
    quantity          numeric(14, 2) not null,
    rate              numeric(14, 2) not null,
    amount            numeric(14, 2) not null,
    advances_deducted numeric(14, 2) not null,
    net_payable       numeric(14, 2) not null,
    notes             varchar(1000),
    status            varchar(20)    not null default 'DRAFT',
    finalized_at      timestamp,
    created_at        timestamp      not null,
    updated_at        timestamp      not null
);

create index idx_bills_month on contractor_bills(period_month);
