-- Gate passes: allow an employee to leave during a shift. Requires attendance on
-- the date; passes beyond the monthly limit (default 3) are penalty-flagged.
-- See com.niic.erp.attendance.GatePassService.

create table gate_passes (
    id           bigint generated by default as identity primary key,
    employee_id  bigint       not null references employees(id),
    date         date         not null,
    out_time     time,
    in_time      time,
    purpose      varchar(500) not null,
    penalty      boolean      not null default false,
    issued_by_id bigint       references users(id),
    created_at   timestamp    not null,
    updated_at   timestamp    not null
);

create index idx_gate_passes_date on gate_passes(date);
create index idx_gate_passes_emp_date on gate_passes(employee_id, date);
