-- Store / Inventory module, layer 1: categories, item master (RM/SFG/FG) with an
-- approval workflow, FG colour/size variants, and a signed stock-transaction
-- ledger (on-hand = sum of quantities). BOM, MRP, POs, bookings, issuance and
-- requisitions are added in later migrations.

create table store_categories (
    id         bigint generated by default as identity primary key,
    name       varchar(255) not null,
    code       varchar(50)  not null unique,
    parent_id  bigint       references store_categories(id),
    created_at timestamp    not null,
    updated_at timestamp    not null
);

create table store_items (
    id               bigint generated by default as identity primary key,
    item_code        varchar(60)    not null unique,
    name             varchar(255)   not null,
    item_type        varchar(10)    not null,
    unit             varchar(30)    not null,
    category_id      bigint         references store_categories(id),
    reorder_level    numeric(16, 3) not null default 0,
    approval_status  varchar(20)    not null default 'PENDING_APPROVAL',
    rejection_reason varchar(1000),
    active           boolean        not null default true,
    created_at       timestamp      not null,
    updated_at       timestamp      not null
);

create index idx_store_items_type on store_items(item_type);
create index idx_store_items_approval on store_items(approval_status);

create table store_variants (
    id         bigint generated by default as identity primary key,
    item_id    bigint       not null references store_items(id) on delete cascade,
    colour     varchar(100) not null,
    size       varchar(50)  not null,
    created_at timestamp    not null,
    updated_at timestamp    not null
);

create index idx_store_variants_item on store_variants(item_id);

create table stock_transactions (
    id            bigint generated by default as identity primary key,
    item_id       bigint         not null references store_items(id),
    variant_id    bigint         references store_variants(id),
    txn_type      varchar(20)    not null,
    quantity      numeric(16, 3) not null,
    txn_date      date           not null,
    reference     varchar(255),
    note          varchar(1000),
    created_by_id bigint         references users(id),
    created_at    timestamp      not null,
    updated_at    timestamp      not null
);

create index idx_stock_txn_item on stock_transactions(item_id);
