-- Store module, layers 2-4: multi-level BOM, stock bookings, purchase orders,
-- issuance challans and material requisitions. MRP is computed, not stored.
-- See the com.niic.erp.store services for the business rules.

-- ---- BOM -------------------------------------------------------------------
create table store_boms (
    id             bigint generated by default as identity primary key,
    output_item_id bigint         not null references store_items(id),
    colour         varchar(100),
    size           varchar(50),
    batch_qty      numeric(16, 3) not null default 1,
    active         boolean        not null default true,
    created_at     timestamp      not null,
    updated_at     timestamp      not null
);

create index idx_boms_output on store_boms(output_item_id);

create table store_bom_components (
    id                bigint generated by default as identity primary key,
    bom_id            bigint         not null references store_boms(id) on delete cascade,
    component_item_id bigint         not null references store_items(id),
    quantity          numeric(16, 4) not null,
    created_at        timestamp      not null,
    updated_at        timestamp      not null
);

-- ---- Bookings --------------------------------------------------------------
create table stock_bookings (
    id          bigint generated by default as identity primary key,
    item_id     bigint         not null references store_items(id),
    variant_id  bigint         references store_variants(id),
    job_id      bigint         not null references jobs(id),
    booked_qty  numeric(16, 3) not null,
    issued_qty  numeric(16, 3) not null default 0,
    status      varchar(10)    not null default 'OPEN',
    created_at  timestamp      not null,
    updated_at  timestamp      not null
);

create index idx_bookings_item on stock_bookings(item_id);
create index idx_bookings_job on stock_bookings(job_id);

-- ---- Purchase orders -------------------------------------------------------
create table purchase_orders (
    id            bigint generated by default as identity primary key,
    po_number     varchar(20) unique,
    supplier_name varchar(255),
    status        varchar(15) not null default 'PENDING',
    notes         varchar(1000),
    created_at    timestamp   not null,
    updated_at    timestamp   not null
);

create table purchase_order_items (
    id                bigint generated by default as identity primary key,
    purchase_order_id bigint         not null references purchase_orders(id) on delete cascade,
    item_id           bigint         not null references store_items(id),
    ordered_qty       numeric(16, 3) not null,
    received_qty      numeric(16, 3) not null default 0,
    rate              numeric(16, 3),
    created_at        timestamp      not null,
    updated_at        timestamp      not null
);

-- ---- Issuance challans -----------------------------------------------------
create table issuance_challans (
    id                bigint generated by default as identity primary key,
    iss_number        varchar(20) unique,
    job_id            bigint       references jobs(id),
    to_workstation_id bigint       not null references workstations(id),
    notes             varchar(1000),
    created_at        timestamp    not null,
    updated_at        timestamp    not null
);

create table issuance_challan_items (
    id         bigint generated by default as identity primary key,
    challan_id bigint         not null references issuance_challans(id) on delete cascade,
    item_id    bigint         not null references store_items(id),
    variant_id bigint         references store_variants(id),
    quantity   numeric(16, 3) not null,
    created_at timestamp      not null,
    updated_at timestamp      not null
);

-- ---- Material requisitions -------------------------------------------------
create table material_requisitions (
    id                  bigint generated by default as identity primary key,
    mr_number           varchar(20) unique,
    from_workstation_id bigint       not null references workstations(id),
    status              varchar(15)  not null default 'PENDING',
    notes               varchar(1000),
    created_at          timestamp    not null,
    updated_at          timestamp    not null
);

create table material_requisition_items (
    id             bigint generated by default as identity primary key,
    requisition_id bigint         not null references material_requisitions(id) on delete cascade,
    item_id        bigint         not null references store_items(id),
    requested_qty  numeric(16, 3) not null,
    fulfilled_qty  numeric(16, 3) not null default 0,
    created_at     timestamp      not null,
    updated_at     timestamp      not null
);
