-- Sampling module: sample lifecycle (draft -> in_review -> selected -> pps_done
-- -> ppm_done -> closed/rejected), revisions (-Rn chains), PPS (fabric, colours,
-- sizes, approval), PPM (5 sections of rows), photos, and admin sample requests.
-- Ported from the legacy attendance_module.html sampling module.

create table samples (
    id                       bigint generated by default as identity primary key,
    sample_no                varchar(30)  not null unique,
    rev_base                 varchar(20)  not null,
    sample_date              date,
    name                     varchar(255) not null,
    style                    varchar(255),
    category                 varchar(255),
    designer                 varchar(255),
    reference                varchar(255),
    notes                    varchar(2000),
    status                   varchar(15)  not null default 'DRAFT',
    closed_remark            varchar(20),
    closed_at                timestamp,
    pps_fabric_details       varchar(2000),
    pps_design_count         int,
    pps_special_instructions varchar(2000),
    pps_saved_at             timestamp,
    pps_approved_at          timestamp,
    pps_approved_by          varchar(100),
    ppm_saved_at             timestamp,
    created_by               varchar(100),
    created_at               timestamp    not null,
    updated_at               timestamp    not null
);

create index idx_samples_base on samples(rev_base);
create index idx_samples_status on samples(status);

-- Bill-of-material-ish lines captured on the sample: raw materials, semi-finished
-- items and operations (line_type = RM | SFG | OP).
create table sample_lines (
    id          bigint generated by default as identity primary key,
    sample_id   bigint       not null references samples(id) on delete cascade,
    line_type   varchar(5)   not null,
    item_id     bigint       references store_items(id),
    name        varchar(255),
    description varchar(500),
    colour      varchar(100),
    qty         numeric(16, 3),
    unit        varchar(30),
    seq         int          not null default 0,
    created_at  timestamp    not null,
    updated_at  timestamp    not null
);

create index idx_sample_lines_sample on sample_lines(sample_id);

-- PPS colour / size options (opt_type = COLOUR | SIZE).
create table sample_pps_options (
    id           bigint generated by default as identity primary key,
    sample_id    bigint       not null references samples(id) on delete cascade,
    opt_type     varchar(10)  not null,
    option_value varchar(100) not null,
    seq          int          not null default 0,
    created_at   timestamp    not null,
    updated_at   timestamp    not null
);

create index idx_sample_pps_options_sample on sample_pps_options(sample_id);

-- PPM detail rows across the five sections (section = SOP | TRIM | MARK | CHECK | PACK).
-- text1/text2 hold the section-specific columns (e.g. SOP: workstation / operation).
create table sample_ppm_rows (
    id         bigint generated by default as identity primary key,
    sample_id  bigint       not null references samples(id) on delete cascade,
    section    varchar(10)  not null,
    seq        int          not null default 0,
    text1      varchar(500),
    text2      varchar(500),
    remark     varchar(1000),
    created_at timestamp    not null,
    updated_at timestamp    not null
);

create index idx_sample_ppm_rows_sample on sample_ppm_rows(sample_id);

-- Photos attached to a sample, tagged by section
-- (section = FORM | PPS | SOP | TRIM | MARK | CHECK | PACK). data_url is a base64
-- image kept inline, mirroring the legacy client-side capture.
create table sample_photos (
    id         bigint generated by default as identity primary key,
    sample_id  bigint       not null references samples(id) on delete cascade,
    section    varchar(10)  not null,
    data_url   text         not null,
    caption    varchar(500),
    seq        int          not null default 0,
    created_at timestamp    not null,
    updated_at timestamp    not null
);

create index idx_sample_photos_sample on sample_photos(sample_id);

-- Admin requests to the sampler: a brand-new sample (NEW) or a change to an
-- existing one (CHANGE). When completed, the sampler links the produced sample.
create table sample_requests (
    id                    bigint generated by default as identity primary key,
    req_type              varchar(10)  not null,
    title                 varchar(255) not null,
    description           varchar(2000),
    priority              varchar(10)  not null default 'NORMAL',
    ref_sample_id         bigint       references samples(id),
    status                varchar(15)  not null default 'PENDING',
    completed_sample_id   bigint       references samples(id),
    requested_by          varchar(100),
    admin_resolved_at     timestamp,
    admin_resolved_by     varchar(100),
    admin_resolved_remark varchar(20),
    created_at            timestamp    not null,
    updated_at            timestamp    not null
);

create index idx_sample_requests_status on sample_requests(status);
create index idx_sample_requests_ref on sample_requests(ref_sample_id);
